os:
  - linux
  - osx
language: nix
sudo: required
# workaround for a macOS specific issue with trusted users
before_install:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - unset LC_CTYPE
script: |
        make
        make test